# Installs servicemonitor resources
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}-create-sm-job
spec:
  template:
    metadata:
      labels:
{{ include "labels.selector" . | indent 8 }}
      name: {{ template "name" . }}-create-sm-job
    spec:
      containers:
        - name: hyperkube
          image: "{{ .Values.global.hyperkube.image }}:{{ .Values.global.hyperkube.tag }}"
          imagePullPolicy: "{{ .Values.global.hyperkube.pullPolicy }}"
          command:
            - ./kubectl
            - apply 
            - -f 
            - /tmp/servicemonitor/*.yaml
          volumeMounts:
            - mountPath: "/tmp/servicemonitor"
              name: tmp-configmap-servicemonitor
      volumes:
        - name: tmp-configmap-servicemonitor
          configMap:
            name: {{ template "name" . }}-create-sm-job
      restartPolicy: OnFailure
      serviceAccountName: {{ template "name" . }}